name: '🌠 功能需求'
description: '提出需求或建议'
title: '[Request] '
labels: ['Feature Request']
body:
  - type: textarea
    attributes:
      label: '🥰 需求描述'
      description: 请提供一个清晰且简洁的描述，说明您希望通过这个功能需求来解决的问题。
    validations:
      required: true
  - type: textarea
    attributes:
      label: '🧐 解决方案'
      description: 请以清晰且简洁的方式描述您希望的解决方案。
    validations:
      required: true
  - type: textarea
    attributes:
      label: '📝 补充信息'
      description: 在这里添加关于问题的任何其他上下文信息。
